-- MySQL Script generated by MySQL Workbench
-- Wed 07 Apr 2021 11:37:16 +04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema epytodo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema epytodo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `epytodo` ;
USE `epytodo` ;

-- -----------------------------------------------------
-- Table `epytodo`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epytodo`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `created at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epytodo`.`todo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epytodo`.`todo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `created at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `due_time` DATETIME NOT NULL,
  `status` ENUM('not started', 'todo', 'in progress', 'done') NULL DEFAULT 'not started',
  `user_id` INT UNSIGNED NULL,
   PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
